### ISSUE TITLE
Where is the source code of the application ?

### ISSUE THREAD

**Issue by kirantpatil** [NordicSemiconductor/nRF-Master-Control-Panel#1]
Hi,

The git repository does not contain any android source related to the project.

Can you please upload the source code.

Thanks.

**Comment by reidarma** [comment]
Hi, and thanks for reaching out to us.

Unfortunately, we do not release the source code for Android MCP.
Currently there is no plans to release the source code. We are however interested in understanding why you desire such access. 
Any feature requests you may have for MCP is interesting as well. 

Best regards,
Martin

**Comment by kirantpatil** [comment]
Namaste,

Greetings from India !!!

We want to develop some apps using your chip and we will also release our
app as opensource.

We would like to see how it is written.

Please release the source code as it would help the community to build more
apps and in turn benefit your chip sales only.

Thanks,
Kiran.

**Comment by reidarma** [comment]
Hi again Kiran, and thanks for coming back to us.

As I understand your points, you should still not expect to see source code for Android MCP being released.
We simply have not designed this to be released as source code. The app is meant to be a helpful tool to enable developers easily debug and test their implementation. 
Our contributions to ease development of applications interacting bluetooth low energy for Android are mainly nRFBeacon and nRF Toolbox.
They are both released with a 3-clause BSD license. 

I hope you find those sufficient. It is great to see that you also are planning to contribute by open sourcing your applications.
We are looking forward to see the products you are creating.

Best regards,
Martin

**Comment by Anonymous941** [comment]
@reidarma It confuses me that [nRF Connect for PC](https://github.com/NordicSemiconductor/pc-nrfconnect-ble), which is essentially the same thing for a different platform, is open source but this isn't, do you mind explaining?  I'm just curious, since most other nRF tools similar to this are open source

**Comment by Anonymous941** [comment]
I'm considering decompiling this at some point

**Comment by philips77** [comment]
Hello @Anonymous941,
Perhaps I would be able to help you without decompiling it? What issue are you facing and why would you be interested in the source code of nRF Connect?
