### ISSUE TITLE
MCP should accept/display both ASCII and HEX input/output

### ISSUE THREAD

**Issue by frief** [NordicSemiconductor/nRF-Master-Control-Panel#12]
It would be nice if MCP would e.g. for Nordic UART Service (or others) be able to send/display arbitrary bytes.

Currently non-printable chars are neither displayed nor can be sent (unless I'm missing something). The app shows "Value:". The log has them though ("value: (0x) 01").

Thanks,

**Comment by philips77** [comment]
Hi @frief, you can now do this. When connected, go to menu and deselect "Parse known characteristics". Then you will have the default message builder and the data will be shown as bytes.

**Comment by frief** [comment]
good, this helped!)

(Probably would not have found this myself for sending because I'd have assumed that "Parse known characteristics" would apply to receiving only)

**Comment by philips77** [comment]
Great. Closing the task.
