### ISSUE TITLE
Location of cloned services

### ISSUE THREAD

**Issue by mainr** [NordicSemiconductor/nRF-Master-Control-Panel#13]
When I select "Clone device's services" menu option, the app informs me of the filename written.

WHERE can I find the file the services are written to? If it is not accessible by a file browser (I'm using Total Commander on Android), how is the stored service file accessed?

I'm assuming the format of this file is human readable...

Thanks.
R. Main.

**Comment by philips77** [comment]
Hi, 
The services are saved in local database of nRF MCP. You can load them and then export to a file by selecting Configure GATT Service in the navigation menu (hamburger menu).
Select your configuration there from drop down list and use menu->export option. It will be saved in SD card in Nordic Semiconductor/Server folder.

**Comment by mainr** [comment]
Thanks. The process was a bit convoluted, I did manage to extract an XML file of the attributes. I'm dissecting the interface of a device, and having a listing of all attributes is handy.
Regards.
