### ISSUE TITLE
AutoReconnect no longer working 

### ISSUE THREAD

**Issue by allenbaker** [NordicSemiconductor/nRF-Master-Control-Panel#6]
In v3.4.1, the "Connect with autoConnect" option works properly and successfully reconnects to the device if the connection is interrupted.  In at least the last two versions, this functionality is broken and does not automatically reconnect to the current device.  I noticed in logcat that gatt.close is being called, which would explain why it is not working.  I do not see that message in v3.4.1 though.

Just a heads up :)

**Comment by philips77** [comment]
Hi, I was told about it already. There will be an update on Friday or Monday with this bug fixed. Thanks for letting us know.

**Comment by allenbaker** [comment]
No problem! Thank you for the prompt response.

**Comment by philips77** [comment]
Hi, I've just released version 4.1. This problem should be fixed now. Let me know if it's not.
Sorry for the delay.
