### ISSUE TITLE
Android BLE unstable

### ISSUE THREAD

**Issue by fantasyRqg** [NordicSemiconductor/nRF-Master-Control-Panel#7]
nrf-51822 bluetooth chipset used in our product. Some customers got bluetooth connection problem(not the distance or power problem). My bluetooth connecting steps are same as Master Control Panel(compare the log). 
Is there any way make app bluetooth connection more stable ?
Any ideas would be appreciated.

**Comment by philips77** [comment]
Hi, please write your question on the https://devzone.nordicsemi.com as it's not quite related to MCP.

What I'd recommend to check is requesting connection interval from the peripheral. Check out this issue https://github.com/NordicSemiconductor/Android-nRF-Beacon-for-Eddystone/issues/1, the fix in the Eddystone connection interval fixed errors 133.
